name: 增强 Enhancement
description: 提供新功能或者现有功能增强建议 Suggest new features or enhancements to existing features
labels: ["Enhancement"]
assignees: "Moriafly"

body:
  - type: markdown
    attributes:
      value: |
        仅仅提交一个建议 Submit just one

  - type: checkboxes
    attributes:
      label: 在反馈此问题前请注意 Please note before reporting this issue
      description: 在提交此反馈前请确认以下内容 Please confirm the following items before submitting this feedback
      options:
        - label: 已经查看相关帮助内容 Read more about the Salt Player help content
          required: true
        - label: 已经在本仓库搜索相关内容（避免重复反馈）Already searched for related content in this repository (to avoid duplicate feedback)
          required: true
        - label: 确认仅将提交**一个**问题（多个问题或者备注提及另外的问题请重新提交新的，如建议 1、2、3 请分开提交。即便是针对某个功能的不太相关的点也应该分开提交，如歌词建议支持大小和颜色调节，应该分开提交大小、颜色的建议）Confirm to submit only one issue (if multiple issues or notes mention other issues, please submit a new one separately)
          required: true

  - type: checkboxes
    id: platform
    attributes:
      label: 平台 Platform
      description: 请选择问题发生的平台（可多选） Please select the platform where the issue occurred
      options:
        - label: Android
        - label: Windows
    validations:
      required: true

  - type: textarea
    attributes:
      label: 描述 Describe
      description: |
        尽量详细的描述 Describe as detailed as possible
      placeholder: 在此输入你的建议 Enter your suggestion here
    validations:
      required: false